fix(scripts): redirect error messages to stderr

diff --git a/.local/bin/switcher_xorg b/.local/bin/switcher_xorg
--- a/.local/bin/switcher_xorg
+++ b/.local/bin/switcher_xorg
@@ -5,7 +5,7 @@
 LINK_PATH="${HOME}/.Xresources"
 
 if [ ! -L "$LINK_PATH" ]; then
-    echo "Error: $LINK_PATH is not a symbolic link."
+    echo "Error: $LINK_PATH is not a symbolic link." >&2
   exit 1
 fi
 
@@ -54,6 +54,6 @@ elif [[ "$filename" == *"light"* ]]; then
     emacsclient --eval "(config-reload)" 1> /dev/null &
 
 else
-    echo "The proper configuration files were not found."
-    exit
+    echo "The proper configuration files were not found." >&2
+    exit 1
 fi
diff --git a/.local/bin/ttybkp b/.local/bin/ttybkp
--- a/.local/bin/ttybkp
+++ b/.local/bin/ttybkp
@@ -28,10 +28,10 @@ main() {
 }
 
 if [ "$#" != 1 ]; then
-    printf "Error. Wrong number of arguments.\n"
+    printf "Error. Wrong number of arguments.\n" >&2
     exit 1
 elif [ ! -f "$1" ]; then
-    printf "Error. The file '%s' does not exist.\n" "$1"
+    printf "Error. The file '%s' does not exist.\n" "$1" >&2
     exit 1
 else
     main "$@"
diff --git a/.local/bin/ttygpg b/.local/bin/ttygpg
--- a/.local/bin/ttygpg
+++ b/.local/bin/ttygpg
@@ -10,7 +10,7 @@ delete_if_exist() {
 	          "$encrypted_file"
 	rm -i "$1"
     else
-	printf "Error. Original file does not exist.\n"
+	printf "Error. Original file does not exist.\n" >&2
 	exit 1
     fi
 }
@@ -21,10 +21,10 @@ main() {
 }
 
 if [ "$#" != 1 ]; then
-    printf "Error. Wrong number of arguments.\n"
+    printf "Error. Wrong number of arguments.\n" >&2
     exit 1
 elif [ ! -f "$1" ]; then
-    printf "Error. The file '%s' does not exist.\n" "$1"
+    printf "Error. The file '%s' does not exist.\n" "$1" >&2
     exit 1
 else
     main "$@"
